### ISSUE TITLE
试了一下，貌似并不可以。。。

### ISSUE THREAD

**Issue by davecat** [jardenliu/wepy-simple-toast#2]

**Comment by jardenliu** [comment]
贴上调用页面的代码

**Comment by davecat** [comment]
https://github.com/davecat/libWepy/blob/aa3700d075278779afa74f58ed1c3444d188f7d7/src/example/index.wpy#L92

**Comment by jardenliu** [comment]
`<template>` 里面添加  `<toast/>`

**Comment by davecat** [comment]
我吃完饭回来检查一下，确实少写组件了。ok了

**Comment by jardenliu** [comment]
enjoy
